### ISSUE TITLE
バス停の情報（画像、説明文など）の収集

### ISSUE THREAD

**Issue by trkoh** [terakawakohei/SandaEzBus#21]
乗り換え地点となるバス停の位置が分かりにくいといった声があるため、それをサポートする情報を載せたい

<img width="412" alt="image" src="https://user-images.githubusercontent.com/51079124/183536774-307012b7-87ec-46cb-9fee-ba24a7cf87f0.png">

アプリでは「中央公園前」, 「ゆり中前」という二つのバス停説明ページを用意する予定

**Comment by trkoh** [comment]
- [ ] 中央公園前、ゆり中前のバス停の周辺の様子がわかる画像をgoogle stretviewでスクショ（notionとかにアップロード)
- [ ] このpdfを参考に、説明を補足
    - https://www.machikyo-akashia.com/2022/04/13/%E3%82%A6%E3%83%83%E3%83%87%E3%82%A3%E3%82%BF%E3%82%A6%E3%83%B3%E5%86%85%E4%B9%97%E7%B6%99%E6%A8%99%E6%BA%96%E6%99%82%E5%88%BB%E8%A1%A8/
    - 乗り換え地点の説明がある
<img width="302" alt="image" src="https://user-images.githubusercontent.com/51079124/183536440-cb20c10f-4b38-4b32-bc82-f7200b437417.png">

**Comment by 10matcho27** [comment]
終わったよ
