### ISSUE TITLE
イベント情報に画像を持たせられるようにする

### ISSUE THREAD

**Issue by trkoh** [terakawakohei/SandaEzBus#63]
- イベントを説明するような画像も入ると嬉しい
- 他に必要な情報があるかも？

**Comment by 10matcho27** [comment]
URL Formを用意できるようにするだけでもいい？

**Comment by 10matcho27** [comment]
#72 
こちらで実装しましょう
https://github.com/terakawakohei/SandaEzBus/issues/72
