### ISSUE TITLE
乗り換えバス停の位置情報モーダル中の閉じるボタンについて

### ISSUE THREAD

**Issue by trkoh** [terakawakohei/SandaEzBus#80]
乗り換え場所案内ページで，各乗り換えバス停の位置情報モーダル中の閉じるボタンが2つある
![image](https://user-images.githubusercontent.com/51079124/198171536-196faca8-a5db-4b69-b484-f42f3e870045.png)

どっちかだけあればいいのかもしれない

**Comment by 10matcho27** [comment]
右上のcloseボタンを消しました
