### ISSUE TITLE
ヘッダー、フッターの実装

### ISSUE THREAD

**Issue by trkoh** [terakawakohei/SandaEzBus#9]
どのページからでもhome（Mapの画面)に移動できるようにしたい

[_app.jsでlayoutの設定をするサンプル](https://reffect.co.jp/react/next-js#i-6)

**Comment by trkoh** [comment]
https://codesandbox.io/s/chakra-ui-header-7pqrh?file=/src/header.js
ヘッダはこれを参考にした気がする

**Comment by 10matcho27** [comment]
おっけー
